Store the PIP cache in a specific directory  - #1149
akuker/RASCSI pull request #1153
Opened 2023-04-28 03:02 UTC by akuker

Updated easyinstall to download the SOURCE pip packages to $HOME/.pip_cache. The web startup script was updated to install the packages from this directory

2023-04-28 03:03 UTC, akuker commented
@rdmark - I'm curious what you think about this change. With the start.sh changes, all of the pip packages will need to be downloaded by easyinstall.sh first. Is this going to be a problem?

We could add some error handling potentially where if the pip install from the cached dir fails, it will try to re-run the command and pull from the internet.

2023-04-28 22:04 UTC, rdmark commented
It's an interesting solution! I can see how we bypass the network instability factor this way. 

A drawback is that the libraries won't ever be refreshed unless you run easyinstall again, but I guess that's acceptable?

Some of the libraries have C extensions that need to be compiled, right? How does this work on an RPi? Does pip3 kick off the compilation on runtime?

2023-06-04 01:53 UTC, rdmark commented
After thinking about it for a while I would argue that giving easyinstall.sh the responsibility to manage the caching of python libraries is a step in the wrong direction. It might make troubleshooting even hairier if f.e. the cached libraries end up in a bad state. Plus it constitutes feature creep for easyinstall. Let's leave the python lib management to pip. ;)

Just my 2 cents!

2023-06-20 02:28 UTC, akuker commented
No objections to me! I'm going to cancel this PR for now. We can dust it off again later if needed.

2023-10-23 12:06 UTC, rdmark commented
I want to try this again!

2023-10-23 15:59 UTC, uweseimet requested changes
On Linux there is already a shared default folder for cached data. Data are usually cached in $HOME/.cache/APPLICATION_NAME, e.g $HOME/.cache/piscsi.
If possible, this convention should be followed.

2023-10-29 06:28 UTC, rdmark commented
Moved the cache dir to `$HOME/.cache/piscsi`. I think that's a fine convention.

The current blocker is that one dependent library has a C wrapper that can't be build from source with pip, so this method doesn't work fully out of the box. Some more research and testing on a real RPi is needed. I'm not targeting this for the upcoming "Bookworm" release.

2023-11-16 04:32 UTC, cefiar commented
For binary packages you can manually specify the platform(s) to download binaries for storage in the local file cache. You'd probably want to separate them out from the existing requirements.txt package list though.

eg: For amd64 it's `python3 -m pip download --only-binary=:all: --platform linux_x86_64 SomePkg`

There are other options that you may want to specify as well, such as python version, ABI, etc. See https://pip.pypa.io/en/stable/cli/pip_download/ - Scroll down to the examples, specifically example 6 for multiple platforms.

Other notes on this:
- May want to consider wrapping the pip pieces in their own functions in a separate shell file, then using `source` in bash to bring it into the easyinstall.sh and web/start.sh scripts (so it's all in one place).
- Could wrap the download functions in a test to see if pypi.org is resolvable by DNS (eg: `getent hosts pypi.org` and check for an exit level not 0) before doing the download, to avoid pip taking ages to fail to connect when not online. This could allow you to try to download the latest files when online (eg: for dev tests) and fail through to the local cache when offline.

2025-12-21 08:49 UTC, rdmark commented
Debian is packaging more and more of these python libraries. I think one path forward is to depend on Debian's packaging.

2026-08-01 21:22 UTC, rdmark commented
Python has now been deprecated

2026-08-01 21:22 UTC, closed without merging