Add debian/ configuration
akuker/RASCSI pull request #30
Opened 2020-08-29 08:59 UTC by sfiera

First cut. Probably don’t want to merge the Drone configuration, since you already have the Github workflow set up. Also probably want a systemd configuration for a proper release.

Sample deb: [rascsi_1.0.0-1_armhf.deb.zip](https://github.com/akuker/RASCSI/files/5144979/rascsi_1.0.0-1_armhf.deb.zip)

2020-08-29 13:34 UTC, akuker commented
Awesome work! 

I don't necessarily have a particular love of the Github workflows. I'll take a look at Drone and see what benefits it provides.

One initial comment - We should probably have separate debs for the Standard and Fullspec versions of the board. I'm not sure how many of either of these are floating around yet. The makefile in the latest pull request will build either with:
make all CONNECT_TYPE=FULLSPEC
or
make all CONNECT_TYPE=STANDARD

The resulting files will be in src/raspberrypi/bin/standard or .../bin/fullspec

2020-08-30 06:51 UTC, sfiera commented
I’m looking at the difference between STANDARD and FULLSPEC and it doesn’t really seem that there’s much code difference, just a few extra pins defined. Does it really need to be a compile-time option to choose between them?

It looks like it wouldn’t be hard to make it a flag or config option, either just `--full-spec` or `--initiator`, or enabling it when a host ID is specified, like `-HD7=host`. I don’t know if the Pi can detect whether the fullspec hardware is attached, but it would be nice to verify.

(My understanding is that the purpose of fullspec is to enable RaSCSI as the host/initiator, but I don’t see a clear explanation of standard vs. fullspec anywhere)

2020-08-30 14:34 UTC, akuker commented
It took a while for me to figure out the difference between them as well. The only difference is the pins that control the direction of the bus transceivers. It does seem like a ton of redundant code for a very simple difference. 

Unfortunately, these is no way for the Pi to know which it is connected to. In hindsight, we could have grounded a gpio to indicate whether it is a fullspec or standard. But hindsight is always 20/20. 

Things get a lot more complicated if we want to support the other board variants. (I think there were 4 or 5) However, I don’t think we need to keep support for those. 

I’m probably one of the few people in the world who as both versions of the board :) I like the idea of integrating these into a single executable, but I think that’s beyond the scope of this PR.

2020-09-04 00:17 UTC, akuker requested changes
I'd just like to change the Makefile back, then I'm good to merging this to master.

2020-09-04 00:17 UTC, akuker commented on src/raspberrypi/Makefile
> +	cp $(BINDIR)/$(RASCSI) $(DESTDIR)$(INSTALL_BINDIR)
This will re-copy the man pages and binaries regardless of whether they have changed or not. This kind of goes against the make file theory, where the rules should show 
target : prerequisite

In this particular case, it doesn't make a big deal, but I've had better luck sticking with this philosophy in the past, especially when you start doing multi threaded make for larger projects.

2020-09-04 00:17 UTC, akuker commented on .drone.yml
> +---
For now, we can just merge this in. At some point, we should either merge this functionality into github workflows, or merge the github workflows into drone.

2020-09-04 00:17 UTC, akuker commented on .drone.yml
> +---
No action for now - resolving comment.

2020-09-04 03:00 UTC, sfiera commented on src/raspberrypi/Makefile
> +	cp $(BINDIR)/$(RASCSI) $(DESTDIR)$(INSTALL_BINDIR)
It will, and I think this is normal for the `install` target. But, it doesn’t make a difference either way to me, as long as the prefix and destdir are there. I’ll look at this later.

2021-09-25 02:19 UTC, akuker commented
This pull request has been overcome by events - the easyinstall.sh script takes care of this.

2021-09-25 02:19 UTC, closed without merging