Updating README.md to reflect the project file structure
akuker/RASCSI pull request #633
Opened 2022-01-31 11:38 UTC by n4al

The project file layout has been modified and those changes should be reflected in the readme file for web interface

2022-01-31 18:21 UTC, rdmark requested changes

2022-01-31 18:21 UTC, rdmark commented on python/web/README.md
> +$ cd python/web/src
The venv should be created in python/web actually.

2022-01-31 18:21 UTC, rdmark commented on python/web/README.md
> +$ BASE_DIR=/tmp/images/ PATH=$PATH:`pwd`/mock/bin/ cd python/web/src && python3 web.py
A litte more code is needed here now, since we have common Python libraries that we need to point to using the PYTHONPATH env variable. If you have a look in python/web/start.sh you'll see what they are.

2022-01-31 18:21 UTC, rdmark commented on python/web/README.md
> +$ cd python/web/src
As per the above comment, the venv should be in python/web

2022-01-31 18:33 UTC, n4al commented on python/web/README.md
> +$ BASE_DIR=/tmp/images/ PATH=$PATH:`pwd`/mock/bin/ cd python/web/src && python3 web.py
Perhaps something like?
`BASE_DIR=/tmp/images/ PATH=$PATH:`pwd`/mock/bin/ cd python/web/src && PYTHON_COMMON_PATH=$(dirname $PWD)/common/src PYTHONPATH=$PWD/src:${PYTHON_COMMON_PATH} python3 web.py`

2022-02-02 04:51 UTC, rdmark approved these changes

2022-02-02 04:51 UTC, merged