Initial version of the Control Board UI
akuker/RASCSI pull request #687
Opened 2022-02-20 15:32 UTC by bzeiss

This is the pull request for the initial version of the Control Board UI. It is mostly self-contained in python/ctrlboard and added as experimental feature as installation point 13) in easyinstall.sh. The installation behavior is that selection of ctrlboard ui disables the rascsi-oled service and vice versa. If 1) is selected (rascsi+web), then the enabled service is updated.

https://github.com/akuker/RASCSI/wiki/RaSCSI-Control-Board

(I'm updating this wiki page further after creating the pull request)

I hope you enjoy this :-)

2022-02-22 05:30 UTC, rdmark requested changes

2022-02-22 05:30 UTC, rdmark commented on python/ctrlboard/README.md
> +* Distributed under DejaVu Fonts Lience (see DejaVu Fonts License.txt for full text)
You couldn't find a nice looking font with a BSD 3-clause compatible license? It a tiny bit unfortunate to have a 'dirty' license situation for an open source distribution.

2022-02-22 05:30 UTC, rdmark commented on python/ctrlboard/service-infra/rascsi-ctrlboard.service
> +ExecStop=/bin/sleep 2
Do you still need this workaround? It doesn't seem like you're using the crappy signal handler class that I added to the OLED script.

2022-02-22 05:30 UTC, rdmark commented on python/ctrlboard/src/ctrlboard_event_handler/ctrlboard_menu_update_event_handler.py
> +            # print(updatedObject.direction)
Leftover debug line?

2022-02-22 05:30 UTC, rdmark commented on python/ctrlboard/src/ctrlboard_event_handler/ctrlboard_menu_update_event_handler.py
> +#                self._menu_controller.segue(result)
Seems redundant

2022-02-22 05:30 UTC, rdmark commented on python/ctrlboard/src/ctrlboard_hw/ctrlboard_hw.py
> +        log = logging.getLogger(__name__)
Thanks for using the logging library correctly. I need to do this in the web code as well. :)

2022-02-22 05:30 UTC, rdmark commented on python/ctrlboard/src/ctrlboard_hw/ctrlboard_hw.py
> +        # print(format(input_register, 'b'))
More leftover debugging prints?

2022-02-22 05:30 UTC, rdmark commented on python/ctrlboard/src/ctrlboard_hw/ctrlboard_hw.py
> +            # print("button press: " + str(button))
One more

2022-02-22 05:30 UTC, rdmark commented on python/ctrlboard/src/ctrlboard_hw/encoder.py
> +        # self.update1()
Debugging?

2022-02-22 05:30 UTC, rdmark commented on python/ctrlboard/src/main.py
> +        info = ractl_cmd.get_server_info()
get_server_info() returns a pretty large response payload. You may save a little bandwidth by polling with something like is_token_auth()

2022-02-22 05:30 UTC, rdmark commented on python/ctrlboard/src/menu/blank_screensaver.py
> +    """Class implementing a blank screen safer that simplay blanks the screen after a
Spelling nitpick: "simply" instead of "simplay"

2022-02-22 05:30 UTC, rdmark commented on python/ctrlboard/src/menu/cycler.py
> +        #        print("loading: " + file_to_load)
Debug line!

2022-02-22 05:30 UTC, rdmark commented on python/ctrlboard/src/menu/cycler.py
> +        #        print("selected: " + str(self.config_files[self.selected_config_file_index]))
one more!

2022-02-22 05:30 UTC, rdmark commented on python/ctrlboard/src/menu/menu_renderer.py
> +                # print("stage 5")
a bunch more commented out debugging lines

2022-02-22 05:30 UTC, rdmark commented on python/ctrlboard/src/menu/menu_renderer.py
> +        # print("position in menu: " + str(self.menu.item_selection))
look at these guys

2022-02-22 05:30 UTC, rdmark commented on python/ctrlboard/src/menu/menu_renderer_config.py
> +#        self.transition = "None"
it's crawling with 'em

2022-02-22 05:30 UTC, rdmark commented on python/ctrlboard/src/menu/menu_renderer_luma_oled.py
> +        #     draw.rectangle((0, 0, self.disp.width-1, self.disp.height-1), outline=0, fill=0)
bugs!

2022-02-22 05:30 UTC, rdmark commented on python/ctrlboard/start.sh
> +#!/usr/bin/env bash
Random musing: Now we have three 'copies' of this script. Can we create a reusable bash library or something? ;)

In all seriousness though, it's a bit of a pain to revise 'em all every time we find an improvement or bug.

2022-02-22 05:31 UTC, rdmark commented on python/ctrlboard/requirements.txt
> +#numpy==1.21.5
Random musing: It's possible to pass the "-j" parameter to pip3 for multi-core compilation which helps a lot.

2022-02-22 20:10 UTC, bzeiss commented on easyinstall.sh
> +# Stops the rascsi-oled service if it is running
correct. fixed.

2022-02-22 20:10 UTC, bzeiss commented on easyinstall.sh
> +# Starts the rascsi-oled service if installed
Correct, fixed.

2022-02-22 20:14 UTC, bzeiss commented on easyinstall.sh
> +      TARGET_I2C_BAUDRATE=400000
Very good suggestion and added exactly that. I think we should take care pointing this out everywhere else (wiki, tindie etc.) too to avoid misunderstandings.

2022-02-22 20:14 UTC, bzeiss commented on easyinstall.sh
> +    echo " 13) install or update RaSCSI Control Board UI (requires hardware)"
True, added that to line 1361.

2022-02-22 20:27 UTC, bzeiss commented on easyinstall.sh
> +    echo "  2) 180 degrees (default)"
That's a good catch. Honestly, I have no idea how to properly rotate it which is probably also why it's inconsistent. If the control board is directly attached on top of the rascsi board and the cable goes out to the back of the desk, it needs to be rotated 180 degrees as you state. However, if rotated by 180 degrees, the board is kinda left handed in that case with the rotary encoder and buttons to the left of the oled. I think I will still go for the 180 degree default as that's probably how people will put it on their desk despite the orientation of the controls.

2022-02-22 20:29 UTC, bzeiss commented on python/ctrlboard/README.md
> +* --transitions: 0 (disabled), 1 (enabled). Default: 1
True, I do support --help and have put proper descriptions in there. So it's indeed redundant. So I have simplified the readme.

2022-02-22 20:53 UTC, bzeiss commented on python/ctrlboard/README.md
> +* Distributed under DejaVu Fonts Lience (see DejaVu Fonts License.txt for full text)
Well, maybe not enough, but to be honest, once you start googling for fonts and font license compatibility at least I am lost in a rabbit hole and I wasn't really happy with the things I found when I tried to find something explicitly under BSD clause 3. It is my understanding that most open source font licenses allow the distribution of the fonts alongside other open source licensend software as long as a font license/credit is distributed next to them and the font isn't merged into the software somehow. In that sense, I don't think it's too dirty. I'm not a lawyer though. The DejaSans/Bitstream Vera license seemed be one of the more straight forward to understand and more liberal licenses to me (allowing even the creation of derivatives) so I thought it would be a rather safe choice. I'm happy for other suggestions though (maybe a proper font site which clearly states licenses and license compatibility that I didn't come across?).

2022-02-22 20:54 UTC, bzeiss commented on python/ctrlboard/service-infra/rascsi-ctrlboard.service
> +ExecStop=/bin/sleep 2
True, it's just copied and adapted without looking too much. I have removed it.

2022-02-22 20:55 UTC, bzeiss commented on python/ctrlboard/src/ctrlboard_event_handler/ctrlboard_menu_update_event_handler.py
> +            # print(updatedObject.direction)
Oh no, there were so many of them. I'm just removing all of them and not commenting each one here.

2022-02-22 20:58 UTC, bzeiss commented on python/ctrlboard/src/ctrlboard_hw/ctrlboard_hw.py
> +        log = logging.getLogger(__name__)
:-)

2022-02-22 21:01 UTC, bzeiss commented on python/ctrlboard/src/main.py
> +        info = ractl_cmd.get_server_info()
changed that.

2022-02-22 21:01 UTC, bzeiss commented on python/ctrlboard/src/menu/blank_screensaver.py
> +    """Class implementing a blank screen safer that simplay blanks the screen after a
fixed

2022-02-22 21:02 UTC, bzeiss commented on python/ctrlboard/src/menu/menu_renderer.py
> +                # print("stage 5")
Yep, by the way: this was a mess to get right. I want to rewrite this part at some point.

2022-02-22 21:08 UTC, bzeiss commented on python/ctrlboard/start.sh
> +#!/usr/bin/env bash
True. Though I suggest to do that in a separate refactoring pull request for all python libs once we have this one done.

2022-02-22 21:16 UTC, bzeiss commented on python/ctrlboard/src/main.py
> +        info = ractl_cmd.get_server_info()
Changed it to get_reserved_id's though for testing. is_token_auth seems to return status: False always when token auth is enabled.

2022-02-22 21:26 UTC, bzeiss commented
@rdmark left a few comments open in case you want to comment further on them. Other than that, I have pushed the changes in 9e53103.

2022-02-23 02:57 UTC, rdmark approved these changes
Overall really cleanly designed codebase, super slick object oriented design. 👍 

To be honest, I didn't evaluate all of the internal logic of all of the classes in depth. I also did not test the functionality, since I don't have the requisite hardware. This approval is on the basis of a high-level real of the codebase, and that I could confirm it has no averse effect on existing packages.

Feel free to put any final touches, and merge when you're ready.

2022-02-23 03:00 UTC, rdmark commented on easyinstall.sh
> +    echo "  2) 180 degrees (default)"
The main usecase I can see for the non-180 degree rotation would be for rack mounting the RaSCSI vertically in, say, a synthesizer rack. Oh, and also a hypothetical scenario where someone designs a case where the OLED and controls are mounted onto the case (side or top) rather than directly on the board.

2022-02-23 03:00 UTC, rdmark commented on python/ctrlboard/start.sh
> +#!/usr/bin/env bash
Sure, it's not in scope for this PR.

2022-02-23 03:01 UTC, rdmark commented on python/ctrlboard/requirements.txt
> +#numpy==1.21.5
Fair point. Compiling C++ code on a Zero is painfully slow. And a Zero 2, despite having multiple cores, runs out of memory with multi core compiling of RaSCSI code.

2022-02-23 03:06 UTC, rdmark commented on python/ctrlboard/README.md
> +* Distributed under DejaVu Fonts Lience (see DejaVu Fonts License.txt for full text)
Interesting that if I read this license correctly, if you modify the font, you can change the license but can't use the trademarked font name anymore. Maybe we can make some tweaks and call it the RaSCSI-Mono-Bold font. =)

I'm mostly joking though. I think I've seen DejaVu fonts used all over the place in FLOSS projects. Come to think of it, it was probably one of the fonts we used with Freeciv back when I was on the maintainer team.

2022-02-23 10:14 UTC, bzeiss commented
@akuker Do you want to give this a test drive before I merge?

2022-02-25 20:03 UTC, merged