Add RASCSI host and port arguments to web/start.sh
akuker/RASCSI pull request #771
Opened 2022-07-25 01:56 UTC by nucleogenic

Allows web/start.sh to accept `--rascsi-host` and `--rascsi-port` arguments, which are then passed through to web.py.

Fixes an issue where web.py errors when the `--rascsi-port` argument is specified.

2022-07-25 01:59 UTC, nucleogenic commented on python/web/start.sh
> -	    ;;
(No change to the arguments here, just replaced tab characters with spaces.)

2022-07-25 04:18 UTC, rdmark requested changes

2022-07-25 04:18 UTC, rdmark commented on python/web/start.sh
> +    -p | --port)
For clarity we should rename the long form for this parameter now, I think. F.e. "--web-port"

2022-07-25 04:18 UTC, rdmark commented on python/web/start.sh
> +        ;;
Please add a one letter parameter for each. Maybe something like -h and -o

2022-07-26 04:18 UTC, nucleogenic commented on python/web/start.sh
> +        ;;
Done.

2022-07-26 04:19 UTC, nucleogenic commented on python/web/start.sh
> +    -p | --port)
Done.

2022-07-26 04:46 UTC, rdmark approved these changes
LGTM. Thanks!

2022-07-26 04:47 UTC, merged