Fix simple SonarCloud issues
akuker/RASCSI pull request #834
Opened 2022-09-04 09:20 UTC by uweseimet

This PR fixes SonarQube issues where the resolution appeared obvious to me and required no refactoring: Missing const, nullptr instead of NULL, empty methods, missing default cases etc.

There are a lot of remaining issues that require closer investigation, but also many that appear to be false positives, e.g. related to constness.

2022-09-05 09:59 UTC, uweseimet commented
@akuker In order not to lose momentum I have already started a second round of addressing SonarCloud issues. There is a new fix_sonarcloud_issues2 (based on fix_sonarcloud_issues). In case you have not yet started reviewing fix_sonarcloud_issues I would like to merge fix_sonarcloud_issues2 into fix_sonarcloud_issues.
Just like with fix_sonarcloud_issues each change in fix_sonarcloud_issues2 usually only affects a single line.

2022-09-06 00:22 UTC, akuker commented
@uweseimet  - I haven't started reviewing yet, so feel free to merge in. I've been diving into the timing issue associated with the new transceivers. Let me know when its ready and I'll dig into it.

As a side note: I bought a SCSI analyzer with amazing accuracy, so I can really see what's going on now.

2022-09-06 06:35 UTC, uweseimet commented
@akuker I have merged fix_sonarcloud_issues2 into fix_sonarcloud_issues. All in all about 800 SonarCloud issues are fixed. The changes now also deal with memory management, making the code more robust against side-effects, and other things. Working on this is a good way to get familiar with more modern C++ features.
I tested everything with my hardware, and the unit tests are passing. This PR is still ready for review.

2022-09-06 12:43 UTC, uweseimet commented
@akuker Regarding the emails with error reports I get, my impression is that they are in particular sent when something is committted while an action for a previous commit is still runing. Not absolutely sure, though.
Regarding this PR, the latest report (above) is outdated, and all builds for changes committed after that report was sent seem to have failed.
And one more thing: I suggest to configure away the coverage checks until supported. Currently quality gates fail because of 0% coverage even when there are no other issues. See https://github.com/akuker/RASCSI/pull/828 for such a report.

2022-09-06 14:30 UTC, uweseimet commented
@akuker Just figured out how to get the compile-time logs. The problem is a compile-time problem only visible with -O3. I will try to find a solution, till then I will put the PR back into draft status.

2022-09-06 14:44 UTC, uweseimet commented
Fixed the compile time error. It was related to a SonarQube (strcpy/strncpy) issue, which may have to be resolved later.

2022-09-06 14:46 UTC, uweseimet commented
Up to date SonarCloud results are now available for this PR.

2022-09-07 01:13 UTC, akuker commented on src/raspberrypi/controllers/abstract_controller.cpp
> +	if (int tmp = id_data - (1 << target_id); tmp) {
I really don't like this....

Couldn't this be written as:
`if(id-data - (1 << target_id)){`

2022-09-07 01:25 UTC, akuker commented on src/raspberrypi/controllers/controller_manager.cpp
> +	if (const auto controller = FindController(id); controller != nullptr) {
Could this be written like this?

`if (FindController(id) != nullptr)`

2022-09-07 02:37 UTC, akuker requested changes

2022-09-07 02:37 UTC, akuker commented on src/raspberrypi/devices/scsi_printer.cpp
> +	if (reservation_time + timeout < time(nullptr)) {
I think this should still be Zero, not null pointer

2022-09-07 02:37 UTC, akuker commented on src/raspberrypi/gpiobus.h
> +// TODO Is this type still relevant?
Yes. Especially since Gimons is no longer maintaining the original RaSCSI. I think these other board types should be retained.

2022-09-07 02:38 UTC, akuker commented
Lots of changes! Thank you for looking into these, @uweseimet . Just a couple comments.

2022-09-07 06:48 UTC, uweseimet commented on src/raspberrypi/devices/scsi_printer.cpp
> +	if (reservation_time + timeout < time(nullptr)) {
time() expects a pointer, not an integer.

2022-09-07 06:53 UTC, uweseimet commented on src/raspberrypi/controllers/controller_manager.cpp
> +	if (const auto controller = FindController(id); controller != nullptr) {
This would not work, because we need the controller in the next line. This is the complete context:

```
	if (const auto controller = FindController(id); controller != nullptr) {
		return controller->GetDeviceForLun(lun);
	}

	return nullptr;

```

2022-09-07 06:55 UTC, uweseimet commented on src/raspberrypi/controllers/abstract_controller.cpp
> +	if (int tmp = id_data - (1 << target_id); tmp) {
This would not work because we need tmp later, i.e. we cannot do without it:

```
	if (int tmp = id_data - (1 << target_id); tmp) {
		initiator_id = 0;
		for (int j = 0; j < 8; j++) {
			tmp >>= 1;
			if (tmp) {
				initiator_id++;
			}
			else {
				break;
			}
		}
	}
```

2022-09-07 06:59 UTC, uweseimet commented on src/raspberrypi/gpiobus.h
> +// TODO Is this type still relevant?
OK.

2022-09-07 07:09 UTC, uweseimet commented
@akuker Thank you for reviewing. I am quite sure that from my side this PR is the last one with so many files being changed in a single PR. The other tickets (even those with major effort) would not affect essentially everything. I hope I am not making wrong promises ;-)
Some changes probably take getting used to, at least for me, because they are using C++ features I was not yet familiar with. When looking at the reasons why SonarCloud made these suggestions, and when looking at the C++ standard, they made a lot of sense. A lot of them reduce the danger of side effects. And some, like structured bindings, make the code much more explicit.

2022-09-07 14:34 UTC, akuker commented on src/raspberrypi/controllers/abstract_controller.cpp
> +	if (int tmp = id_data - (1 << target_id); tmp) {
You are correct. I didn't look down far enough.

2022-09-07 14:35 UTC, akuker commented on src/raspberrypi/gpiobus.h
> +// TODO Is this type still relevant?
thanks!

2022-09-07 14:37 UTC, akuker commented
> @akuker Thank you for reviewing. I am quite sure that from my side this PR is the last one with so many files being changed in a single PR. The other tickets (even those with major effort) would not affect essentially everything. I hope I am not making wrong promises ;-) And provided that there are not too many issues of this kind still being reported. I don't know why, but the issues reported by SonarLint within Eclipse do not always match those reported in the SonarCloud UI, even though SonarLint connects to the SonarCloud server and gets its settings from this server.

There might be settings we need to tweak in SonarCloud. I think I added you to the project, but I'm not sure if that gives you access to the settings or not.
 
> Some changes probably take getting used to, at least for me, because they are using C++ features I was not yet familiar with. When looking at the reasons why SonarCloud made these suggestions, and when looking at the C++ standard, they made a lot of sense. A lot of them reduce the danger of side effects. And some, like structured bindings, make the code much more explicit.

These new features of C++ are new to me as well. I learned quite a bit from reviewing your changes, so thank you! :)

As a former Ada programmer, the `auto` keyword scares me..... Why would you want to use a variable if you don't explicitly define what its type is!! But, I can see the value in it.

2022-09-07 14:38 UTC, akuker approved these changes

2022-09-07 14:38 UTC, merged

2022-09-07 14:41 UTC, uweseimet commented
@akuker auto is similar to var/val etc. in other languages, and I do not use it everywhere. SonarCloud also does not propose to use it everywhere. It suggests to use it only when you can immediately see the type from the rvalue.

2022-09-07 15:29 UTC, uweseimet commented
@akuker Regarding SonarCloud settings, being a project member is not sufficient. I would need to be able to create new quaiity profiles.