Code cleanup based on SonarQloud report
akuker/RASCSI pull request #845
Opened 2022-09-16 19:03 UTC by uweseimet

2022-09-18 15:55 UTC, uweseimet commented
@akuker Have you already started with reviewing this PR? If not, and in case you agree, I would like to add the changes from the feature_more_code_cleanup branch to this PR.

2022-09-19 15:34 UTC, akuker commented
> @akuker Have you already started with reviewing this PR? If not, and in case you agree, I would like to add the changes from the feature_more_code_cleanup branch to this PR.

Hi @uweseimet - No I have not started reviewing this PR yet. Sorry for the delay! I'm on travel for work this week. Feel free to pull more stuff in and let me know when you're done. I'll be stuck in an airport Tuesday afternoon if its ready by then.

2022-09-20 02:19 UTC, nucleogenic commented on src/raspberrypi/config.h
> +#if defined(__x86_64__) || defined(__X86__)
It might be nice to use a specific parameter to tell the compiler that we are building for a platform without RaSCSI hardware. This check will assume we want hardware support when compiling from Linux on aarch64, which isn't always the case.

2022-09-20 06:24 UTC, uweseimet commented on src/raspberrypi/config.h
> +#if defined(__x86_64__) || defined(__X86__)
@nucleogenic Yes, that's what I also think. This can be addressed in a different (future) PR.

2022-09-20 09:31 UTC, uweseimet commented
@akuker I have added all of my pending changes, i.e. this PR is ready for review.

2022-09-20 22:03 UTC, akuker commented
@uweseimet - one minor comment, then it looks ready to merge.

2022-09-20 22:03 UTC, akuker requested changes

2022-09-20 22:10 UTC, uweseimet commented on src/raspberrypi/hal/gpiobus.h
> +	inline int Acquire() override
@akuker This change is wrong, indeed. Obviously I missed here that DWORD is uint32_t. I just changed the data type to uint32_t, which is identical with tDWORD.

2022-09-20 22:33 UTC, akuker commented on src/raspberrypi/hal/gpiobus.h
> +	inline int Acquire() override
Thanks Uwe!

2022-09-20 22:34 UTC, akuker approved these changes

2022-09-20 22:34 UTC, akuker commented
I'm on my mobile, so I'll let you do the merge, in case something goes wrong.

2022-09-21 06:21 UTC, uweseimet commented
@akuker OK. Thank you for reviewing!

2022-09-21 06:27 UTC, merged