More unit tests, replacement of raw pointers, fixed SonarCloud issues
akuker/RASCSI pull request #878
Opened 2022-10-01 16:06 UTC by uweseimet

2022-10-03 00:57 UTC, akuker requested changes

2022-10-03 00:57 UTC, akuker commented on src/raspberrypi/devices/ctapdriver.cpp
> +#ifdef __linux
Why was this changed? According to this page (http://www.faqs.org/docs/Linux-HOWTO/GCC-HOWTO.html#INDEX.25) __linux__ is recommended over __linux

2022-10-03 00:57 UTC, akuker commented on src/raspberrypi/devices/file_support.cpp
> +		Open(filepath);
Should this be closed after its opened?

2022-10-03 00:57 UTC, akuker commented on src/raspberrypi/rascsi.cpp
> +#if !defined(USE_SEL_EVENT_ENABLE) && defined(__linux)
Similar to above - would __linux__ be more appropriate?

2022-10-03 07:22 UTC, uweseimet commented on src/raspberrypi/devices/ctapdriver.cpp
> +#ifdef __linux
I'm fine with anything here. As long as it is correct, of course ;-). The old code from last year uses __linux__,  the current code was inconsistent (thus my change, so that the same definition is used everywhere), but the preprocessor has linux, __linux and __linux__.
It's up to you to make the decision, I will change it accordingly everywhere.

2022-10-03 07:45 UTC, uweseimet commented on src/raspberrypi/devices/file_support.cpp
> +		Open(filepath);
Indeed, it should. But the Disk class (where the Open comes from) does not have a Close() ...
I have a much better and simpler solution now: standard C++ filesystem::exists().
This example shows once more that *not* using the legacy filesystem code (fileio.cpp/filepath.cpp) is a good idea. IMO, one should get rid of filesystem/fileio/filepath.cpp. The result would be less complicated and more transparent.

2022-10-03 07:46 UTC, uweseimet commented on src/raspberrypi/rascsi.cpp
> +#if !defined(USE_SEL_EVENT_ENABLE) && defined(__linux)
@akuker To be honest, I don't know what's best. This is why I would like you to decide ;-). In any case, it should be consistent.

2022-10-03 08:14 UTC, uweseimet commented
@akuker Regarding the Open() functionality, further testing revealed that if Open() is not called there are issues, because Open() has side-effects` on the device status ...
I will have to investigate this further in order to find a clean solution, and will get back to you when I am done.

2022-10-03 10:56 UTC, uweseimet commented
@akuker OK, the resolution is not to change anything but to add a comment in FileSupport for transparency. Reason: Disk::Open() closes the file if it can successfully be opened. It has always done so, even in v21.05.01, see this code snippet:
```
        // Can read/write open
        if (fio.Open(path, Fileio::ReadWrite)) {
                // Write permission, not read only
                disk.writep = FALSE;
                disk.readonly = FALSE;
                fio.Close();
        } else {
                // Write protected, read only
                disk.writep = TRUE;
                disk.readonly = TRUE;
        }
```

2022-10-04 02:41 UTC, akuker commented on src/raspberrypi/rascsi.cpp
> +#if !defined(USE_SEL_EVENT_ENABLE) && defined(__linux)
I vote for __linux__ to be consistent.

2022-10-04 02:42 UTC, akuker commented on src/raspberrypi/devices/ctapdriver.cpp
> +#ifdef __linux
I vote for `__linux__`, since the random internet article says so :)

2022-10-04 02:43 UTC, akuker commented on src/raspberrypi/rascsi.cpp
> +#if !defined(USE_SEL_EVENT_ENABLE) && defined(__linux)
> @akuker OK, the resolution is not to change anything but to add a comment in FileSupport for transparency. Reason: Disk::Open() closes the file if it can successfully be opened. It has always done so, even in v21.05.01, see this code snippet:
> 
> ```
>         // Can read/write open
>         if (fio.Open(path, Fileio::ReadWrite)) {
>                 // Write permission, not read only
>                 disk.writep = FALSE;
>                 disk.readonly = FALSE;
>                 fio.Close();
>         } else {
>                 // Write protected, read only
>                 disk.writep = TRUE;
>                 disk.readonly = TRUE;
>         }
> ```

Works for me!

2022-10-04 08:07 UTC, uweseimet commented
@akuker Unless I have missed something it's __linux__ now everywhere.

2022-10-04 15:14 UTC, akuker approved these changes

2022-10-04 15:14 UTC, akuker commented
@uweseimet - Merge away! Thanks :)

2022-10-04 15:19 UTC, uweseimet commented
@akuker Good news, thank you!

2022-10-04 15:23 UTC, merged