Address Sonarcloud issues for the html code; improve on css styles
akuker/RASCSI pull request #892
Opened 2022-10-05 02:43 UTC by rdmark

2022-10-05 02:44 UTC, rdmark commented
@uweseimet FYI, I'm addressing issues reported by SonarCloud for the html code here.

I've also tweaked the rules so that we may see more structural and semantic issues raised in the next report.

2022-10-05 07:14 UTC, uweseimet commented
@rdmark Regarding SonarCloud, any news on making the develop branch a long-living branch?

2022-10-05 18:30 UTC, akuker commented
> 

I don't agree with the "GNU extensions should not be used" rule. When are we going to use a non-GNU compiler?

I'm OK with trying these to see what happens. But, I'd like to move past the huge PRs that don't fix functional issues or add features. Around October 15th or so, I'd like to lock down the code base to only bug fixes so we can shoot for a stable release at the end of the month.

2022-10-05 18:35 UTC, uweseimet commented
@akuker Sounds fine for me. Regarding the GNU extension settings I don't consider it important. i was just curious whether there is actually anything GNU specific being used.

2022-10-06 00:05 UTC, nucleogenic reviewed
I've given this a first pass. It's definitely looking a lot cleaner already.

A sprinkling of somewhat nitpicky comments.

I've done some basic testing in Netscape 4.08, Classilla, iCab, etc and didn't notice any major issues.

2022-10-06 02:27 UTC, rdmark commented on python/web/src/web.py
> +        locale=get_locale(),
Great idea, I didn't realize how versatile get_env_info() is.

That got me thinking, why don't we expose the entire server_info dictionary in env? Then the Jinja template can query the dictionary for whatever it needs, e.g. env["server_info"]["image_dir"] etc. It would cut down on the clutter of index() in particular.

2022-10-06 02:35 UTC, rdmark commented on python/web/src/templates/index.html
> +                    <input name="unit" id="unit" type="number" value="0" min="0" max="31" step="1">
Whoops, the unique id requirement completely slipped my mind. It'll be a chore, but I'll make sure ids are unique.

As to the LUN input fields, a ```number``` type input field doesn't actually take a size attribute unfortunately. It is up to each browser to interpret how wide the field should be based on the min and max attributes.  https://www.w3schools.com/tags/att_input_type_number.asp

Using ```number``` gives us "free" html5 input validation which is handy. But perhaps we can try CSS styling to control the width in modern browsers?

2022-10-06 03:10 UTC, rdmark commented on python/web/src/templates/base.html
> +        <span class="header" id="logged_in">
I knew there were more semantic improvements to be made to that title header! Looks much better now.

2022-10-06 03:12 UTC, rdmark commented on python/web/src/templates/base.html
> +            {{ _("Web Interface Authentication Disabled") }} &#8211; {{ _("See <a href=\"%(url)s\" target=\"_blank\">Wiki</a> for more information", url="https://github.com/akuker/RASCSI/wiki/Web-Int
Good call. Fixed.

2022-10-06 03:13 UTC, rdmark commented on python/web/src/static/style.css
> +  width: 100%;
Lol, yeah you're right. I wonder what the original intent was here?

2022-10-06 03:13 UTC, rdmark commented on python/web/src/static/style.css
> +  vertical-align: center;
Fixed.

2022-10-06 03:14 UTC, rdmark commented on python/web/src/static/style.css
>  }
Fixed. Before you helped me get rid of the spans, I ran into trouble overriding CSS classes in child elements.

2022-10-06 03:16 UTC, rdmark commented on python/web/src/static/style.css
> +  border: 2px solid #4CAF50; /* Green */
Let's make it blue for it to stand out a little better. :)

2022-10-06 03:17 UTC, rdmark commented on python/web/src/templates/index.html
> +    <label for="name">{{ _("File name") }}</label>
Fixed!

2022-10-06 11:40 UTC, nucleogenic commented on python/web/src/web.py
> +        "base_dir": server_info["image_dir"],
Maybe a good opportunity to rename this to `image_dir`.

I couldn't see any examples where `base_dir` had another meaning.

2022-10-06 11:49 UTC, nucleogenic commented on python/web/src/web.py
> -        version=server_info["version"],
Very pleased to see this and some of the other server_info data moved out of the individual `response` calls. It's much cleaner! 🎆

2022-10-06 16:19 UTC, rdmark commented on python/web/src/web.py
> +        "base_dir": server_info["image_dir"],
Good idea. The base_dir naming is a remnant of an era when we stored everything in the image dir. Time to clean it up.

2022-10-06 22:06 UTC, rdmark commented on python/web/src/web.py
> +        locale=get_locale(),
I see your point. I can see how it'll be easier to manage future change by exposing only the variables that are actively used by the Web UI.

2022-10-06 22:17 UTC, rdmark commented on python/web/src/templates/index.html
> +                    <input name="unit" id="unit" type="number" value="0" min="0" max="31" step="1">
Oh interesting. Which browsers that you tried respect the size attribute for numeric input fields?
Anyhow, I've added the size attribute now!

2022-10-06 22:20 UTC, rdmark commented on python/web/src/web.py
> -        version=server_info["version"],
Agreed! The code duplication between index() and drive_list() has been bothering me for a long time. It's much cleaner now. I also sorted the response parameters in index() to make it a bit more readable.

2022-10-06 23:27 UTC, nucleogenic requested changes
Can you check drive creation from the named drives page? Getting an error here.

2022-10-06 23:27 UTC, nucleogenic commented on python/web/src/templates/drives.html
>      </td>
BTW, it's perfectly valid to use `<td align="center">` in HTML 4.01 and below.
https://www.w3.org/TR/html4/struct/tables.html#adef-align-TD

I feel like we're probably adhering to HTML 4.01, but non-strictly in the sense that it's okay to use more modern features from HTML 5 as long as they gracefully degrade.

2022-10-06 23:27 UTC, nucleogenic commented on python/web/src/templates/drives.html
> -        <input type="hidden" name="drive_name" value="{{ hd.name }}">
Accidentally removed?

2022-10-07 02:51 UTC, rdmark commented on python/web/src/templates/drives.html
>      </td>
It might be a good idea to run the code against an html4 validator and see what suggestions we get. I've been kind of playing it by ear, from what I remember when doing webcoding circa 1999.

The align="center" attribute works great also in Netscape 3!

2022-10-07 02:52 UTC, rdmark commented on python/web/src/templates/drives.html
> -        <input type="hidden" name="drive_name" value="{{ hd.name }}">
Indeed. Merge conflict fail.

2022-10-07 17:54 UTC, nucleogenic approved these changes

2022-10-07 20:13 UTC, merged