Merged FileSupport into Disk, improved granulary, more unit tests, code cleanup
akuker/RASCSI pull request #897
Opened 2022-10-06 20:44 UTC by uweseimet

This is a new attempt to create a proper PR for the original feature_merge_file_support branch, which had strange merging issues.

Most relevant changes:

- Merged FileSupport into Disk
- Improved code granularity
- Made classes previously directly writing to cout testable
- Added numerous unit tests (total test count is 144)
- Fixed SonarCloud issues
- Replaced remaining proprietary data types (WORD/DWORD) except for files in hal/
- Fixed formatting inconsistencies (curly braces)

2022-10-07 22:27 UTC, akuker requested changes

2022-10-07 22:27 UTC, akuker commented on src/raspberrypi/devices/device_factory.cpp
> +	        strcpy(ifr.ifr_name, tmp->ifa_name); //NOSONAR Using strcpy is safe here
I think we can change this to the following and avoid the NOSONAR tag

```
strncpy(ifr.ifr_name, tmp->ifa_name, IFNAMSIZ);
```

2022-10-07 22:27 UTC, akuker commented on src/raspberrypi/devices/scsi_printer.cpp
> +		strcpy(filename, TMP_FILE_PATTERN); //NOSONAR Using strcpy is safe here
Suggest:

```
strncpy(filename, TMP_FILE_PATTERN, TMP_FILENAME_LENGTH);
```

and get rid of the NOSONAR tag

2022-10-08 07:28 UTC, uweseimet commented on src/raspberrypi/devices/scsi_printer.cpp
> +		strcpy(filename, TMP_FILE_PATTERN); //NOSONAR Using strcpy is safe here
This results in
```
/devices/scsi_printer.cpp:220:24: warning: ‘char* strncpy(char*, const char*, size_t)’ output truncated before terminating nul copying 23 bytes from a string of the same length [-Wstringop-truncation]
  220 |                 strncpy(filename, TMP_FILE_PATTERN, TMP_FILENAME_LENGTH);
```
I tried this solution before, because I try to avoid NOSONAR whereever I can, but I did not find a solution.

2022-10-08 07:33 UTC, uweseimet commented on src/raspberrypi/devices/device_factory.cpp
> +	        strcpy(ifr.ifr_name, tmp->ifa_name); //NOSONAR Using strcpy is safe here
I will commit this change, but I don't think it will help, because SonarCloud also complains about strncpy, as you can see in the SonarCloud security review, e.g. https://sonarcloud.io/project/security_hotspots?id=akuker_RASCSI&branch=feature_merge_file_support_into_disk&sinceLeakPeriod=true.
But let's give it a try. If this change has no effect I will keep it, because I like it better than my previous code, but I may have to re-add NOSONAR.
Unfortunately the SonarLint Eclipse plugin is not reliable and reports other (often wrong) issues than SonarCloud, i.e. I have to commit changes like this in order to see the effect. This is what caused the huge number of commits I needed for fixing SonarCloud issues.

2022-10-08 08:08 UTC, uweseimet commented on src/raspberrypi/devices/device_factory.cpp
> +	        strcpy(ifr.ifr_name, tmp->ifa_name); //NOSONAR Using strcpy is safe here
SonarCloud also complains about strncpy, thus I re-added NOSONAR.

2022-10-08 09:50 UTC, uweseimet commented
@akuker Please note that I added a fix to the logging output. I stumbled upon this while testing.

2022-10-08 17:21 UTC, akuker approved these changes

2022-10-08 17:22 UTC, akuker commented
Approved! Thank you for investigating the strcpy thing!

2022-10-08 17:23 UTC, uweseimet commented
@akuker Thank you for reviewing!

2022-10-08 17:26 UTC, merged