Resolved issues 772, 827, 909; added numerous unit tests; code cleanup
akuker/RASCSI pull request #915
Opened 2022-10-15 12:52 UTC by uweseimet

This PR resolved 3 issues which all required moving existing code between classes. The most important changes:

- Resolved issues 772, 827, 909
- Improved error handling, e.g. more precise SCSI error codes
- Improved encapsulation
- Removed duplicate code
- Added numerous unit tests

2022-10-17 05:33 UTC, rdmark commented
@uweseimet FYI, Tony was busy taking care of a family situation this weekend so the release hasn't been tagged yet.

2022-10-21 23:45 UTC, rdmark commented
@uweseimet The 22.10 release has been tagged now. We can unfreeze the develop branch.

2022-10-22 07:01 UTC, uweseimet commented
I noticed that there is a 22.10.01 tag now, so I assume the develop branch is open again for merging. I am going to finalize this PR.

2022-10-22 07:36 UTC, uweseimet commented
@rdmark By the way, would you mind waiting for my upcoming changes for issue 911 to be merged before restructuring? These changes add, rename and remove some files, and it would be great if this could be done before restructuring.
After the changes for issue 911 I have not planned any changes that would collide with moving files around.

2022-10-23 02:05 UTC, akuker requested changes

2022-10-23 02:05 UTC, akuker commented on src/raspberrypi/test/rasutil_test.cpp
> +	EXPECT_EQ("ext", GetExtensionLowerCase("file.ext"));
Should we add some test cases for extensions that are not 3 characters? What about a test for no extension?

2022-10-23 14:43 UTC, uweseimet commented on src/raspberrypi/test/rasutil_test.cpp
> +	EXPECT_EQ("ext", GetExtensionLowerCase("file.ext"));
Done. The 3 character case is not a special case, though. It's special for humans, but not for a software implementation. But "." is a case that is special, and I added a test for it.

2022-10-23 14:47 UTC, uweseimet commented on src/raspberrypi/scsi.h
> -		CONDITION_MET = 0x04,
There are several reasons:

- These enum values had no purpose, because they were not used
- Unused enum values make the code metrics worse
- SonarCloud may report issues if not all enum values are not handled in a switch, because the implementation may be incomplete, i.e. the code that was supposed to handle a particular enum value is missing. Having warnings in such a case is especially important if a new value is added, because you may miss code locations (switches) were you would have to deal with this value. This is also why default cases can be an issue.
- An inconsistency was removed, bcause we do not have other enums with unused values.

2022-10-23 14:48 UTC, uweseimet commented on src/raspberrypi/scsi.h
> -		BLANK_CHECK = 0x08,
Same reasons as above.

2022-10-23 19:47 UTC, akuker commented on src/raspberrypi/scsi.h
> -		CONDITION_MET = 0x04,
Ok. Works for me

2022-10-23 19:48 UTC, akuker approved these changes

2022-10-23 19:48 UTC, akuker commented
Approved. Feel free to merge this @uweseimet . Thanks!

2022-10-23 19:51 UTC, merged

2022-10-23 19:52 UTC, uweseimet commented
@akuker Thank you. I just merged and added a summary of the most relevant changes to the merge message.