Update GitHub Actions
akuker/RASCSI pull request #974
Opened 2022-11-08 17:52 UTC by nucleogenic

# Introduction

This change set contains proposed changes to the GitHub Actions workflows for the project.

🔔 **Note:** This is an early draft PR for feedback as CI workflows impact all contributors.

(A PR is also required to test the GitHub Actions `pull_request` event.)

# Changes

* Added web UI workflow (currently runs `flake8` and `black`)
* Fixed broken/false positive C++ unit test execution step
* Split SonarCloud analysis into a separate job (allows unit tests to run independently/in parallel)
* Prevented SonarCloud job from running on forks
* Added cache for SonarCloud installation
* Added cache for SonarCloud scanning (branch-level cache)
* Added parallel build jobs for ARM cross-compilation

# Execution Behaviour

* Event: push
  * Run ARM build workflow and C++ workflow only if cpp/** changed
  * Run web UI workflow only if python/** changed
* Event: pull_request
  * Run all workflows

# Ideas/Improvements

These may be implemented here, or on a future branch, depending on time/complexity.

* ARM parallel build
  * Performance improvement? If not, consider reverting to sequential build
  * Update `uses` property to `@develop` before merge?
* Web UI workflow
  * Run web UI test suite
  * Add SolarCloud scan against Python sources
* SonarCloud cache
  * Build cache against develop branch to speed up first execution on branches off develop

2022-11-10 02:37 UTC, akuker commented on .github/workflows/build_code.yml
> +    uses: akuker/RASCSI/.github/workflows/arm_cross_compile.yml@nucleogenic-update-github-actions
Is the `@nucleogenic-update-github-actions` part of this only needed because its currently in a different forked repo? This won't be necessary after it merges in, right?

2022-11-10 02:38 UTC, akuker commented on .github/workflows/build_code.yml
> +      connect-type: "FULLSPEC"
Does it run these in parallel? Otherwise, it seems like it would take longer to build if they're in series (since you have to setup the environment twice)

2022-11-10 08:56 UTC, nucleogenic commented
> @nucleogenic Note that the sonar.cfamily.cache.enabled option is deprecated and will be removed with the next major SonarQube release. The SonarQube documentation contains the details.

Hi @uweseimet, thanks for making me aware.

I can see the deprecation notice in the SonarQube docs:
https://docs.sonarqube.org/latest/analysis/languages/cfamily/

Looking at the SonarCloud docs, this doesn't seem to be deprecated yet?
https://docs.sonarcloud.io/advanced-setup/languages/c-c-objective-c/

I can't find any reference to the new properties being available for SonarCloud.

2022-11-10 09:03 UTC, uweseimet commented
@nucleogenic As far as I can tell SonarCloud is regularly updated with the latest SonarQube version. Since SonarCloud is a hosted SonarQube instance as far as properties are concerned they are those also supported by SonarQube.
Saying that, I expect it to be just a matter of time until changes in SonarQube become relevant for SonarCloud. The cache behavior/option will change in the *next* major SonarQube version, that's why this property is still available in SonarCloud.

2022-11-10 10:44 UTC, nucleogenic commented
I tried introducing the new properties, but they were ignored.

The scanner gives this output:

```
to enable cache please specify the following 2 options:
sonar.cfamily.cache.enabled=true
sonar.cfamily.cache.path=relative_or_absolute_path_to_cache_location

* visit the documentation page for more information
https://docs.sonarcloud.io/advanced-setup/languages/c-c-objective-c/
```

(https://github.com/akuker/RASCSI/actions/runs/3435586763/jobs/5728119135)

I also checked to see if we are using the latest scanner version, which we seem to be:

`SONAR_SCANNER_VERSION: 4.7.0.2747`

https://docs.sonarcloud.io/advanced-setup/ci-based-analysis/sonarscanner-cli/
https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/

I am not familiar enough with the SonarSource solutions to provide any further insight beyond we're not getting deprecation warnings at the moment. Regardless, it will be an easy change to make in the future.

2022-11-10 10:50 UTC, uweseimet commented
@nucleogenic I'm not sure whether I correctly understand: The respective option can become ineffective any time. When this happens, what is going to be the impact? If there is any impact, how will it be resolved, i.e. what is the easy change?

2022-11-10 11:01 UTC, uweseimet commented
@nucleogenic One more question regarding "Fixed broken/false positive C++ unit test execution step". What was broken here? I'm asking because I have not noticed anything that does not work with the C++ unit tests and the C++ code analysis.

2022-11-10 11:03 UTC, nucleogenic commented
@uweseimet My current understanding is that the properties are not deprecated in SolarCloud yet. Can you provide a source to suggest otherwise? I can't find one.

The properties can be renamed easily in the future, of course, when they are supported.

Let me know if you have any concerns?

2022-11-10 11:09 UTC, uweseimet commented
@nucleogenic I would like to learn what is going to happen once these properties are not supported anymore. This can happen any time with a SonarCloud maintenance update. What will be the impact on the github action, and what has to be done in order to fix that? What does have to be renamed how?
If properties are added and it is already known at the time of adding them that they are going to be removed it is important to know how to address issues their removal will cause.

2022-11-10 13:00 UTC, nucleogenic commented
> @nucleogenic I would like to learn what is going to happen once these properties are not supported anymore. This can happen any time with a SonarCloud maintenance update.

The new properties don't appear to be supported via SonarCloud yet, so it doesn't appear to be an option for us to update them right now. You could apply this argument to any feature of SonarCloud, of course.

> What will be the impact on the github action, and what has to be done in order to fix that? What does have to be renamed how?

The change would be:

```
Remove:
--define sonar.cfamily.cache.enabled=true
--define sonar.cfamily.cache.path="$HOME/.sonar_cache/"

Add:
--define sonar.cfamily.analysisCache.mode=fs
--define sonar.cfamily.analysisCache.path="$HOME/.sonar_cache/"
```

Interestingly, the docs state SonarQube defaults to `sonar.cfamily.analysisCache.mode=server`, which might reduce some of the cache management burden from us, if this is supported via SonarCloud.

> If properties are added and it is already known at the time of adding them that they are going to be removed it is important to know how to address issues their removal will cause.

There isn't a deprecation notice - as far as I can see - in the SonarCloud documentation. Since SonarQube is in practice a separate offering, I think we can only make decisions based on the SonarCloud docs.

2022-11-10 13:08 UTC, nucleogenic commented
> @nucleogenic One more question regarding "Fixed broken/false positive C++ unit test execution step". What was broken here? I'm asking because I have not noticed anything that does not work with the C++ unit tests and the C++ code analysis.

See here (before):
https://github.com/akuker/RASCSI/actions/runs/3436315899/jobs/5729699222

<img width="688" alt="image" src="https://user-images.githubusercontent.com/22725053/201098853-d63fe947-c5a3-4786-a474-237cd9ea4793.png">

Vs here (after):
https://github.com/akuker/RASCSI/actions/runs/3435587007/jobs/5728119583

<img width="688" alt="image" src="https://user-images.githubusercontent.com/22725053/201099241-e694052a-6b2c-41c5-92ac-93aabf361c97.png">

When the command returned a non-zero exit code (e.g. command error, failing tests), GitHub Actions still reported the step as successful, because `tee` always returned a zero exit code.

2022-11-10 13:22 UTC, uweseimet commented
@nucleogenic Thanks a lot for elaborating on the SonarQube property issue and on the C++ analysis issue!

Regarding SonarCloud, it is essentially a SonarQube instance, so anything related to SonarQube will also become relevant for SonarCloud, SonarCloud cannot be that different from SonarQube, because they are just running SonarQube in a special environment. This is quite similar to the relationship of Jenkins to CloudBees, for instance, the latter offering a multi-team solution on top of Jenkins.

2022-11-10 14:22 UTC, nucleogenic commented on .github/workflows/build_code.yml
> +    uses: akuker/RASCSI/.github/workflows/arm_cross_compile.yml@nucleogenic-update-github-actions
I could only see examples that used the fully qualified (e.g. with branch or tag) path, so the intention was to  update it to `develop` before merging. I will see what happens without the `@suffix` first though; if it just uses the version on the current branch that will be much more convenient.

2022-11-16 00:46 UTC, akuker requested changes

2022-11-16 01:51 UTC, nucleogenic commented on .github/workflows/cpp.yml
> +  pull_request:
So the _assumptions_ I made here were:

- Devs run unit tests locally and test compilation while the feature is WIP
- While a PR is open, all pushes will trigger the workflow, as a push triggers a pull_request synchronize event
- Open a PR in draft to start getting SonarCloud analysis, or early passive reviews

If you want the workflow to run on branches which don't have a draft PR open (e.g. because it's a pain to compile locally) then we should change this back to `push` and perhaps `pull_request[opened]` (else I don't believe it will run against a PR from a fork.)

A lot of this is personal preference, so happy to make whatever change works for you. We have a separate workflow for the web stuff, so they don't have to be the same.

2022-11-16 02:17 UTC, akuker commented on .github/workflows/cpp.yml
> +  pull_request:
> Devs run unit tests locally and test compilation while the feature is WIP

You underestimate my laziness :)

As long as it runs when there is a draft PR, I'm good with it as-is. I just researched the `workflow_dispatch` tag, and that will work fine for running sonarcloud analysis.

Comment withdrawn!

2022-11-16 03:44 UTC, nucleogenic commented on .github/workflows/cpp.yml
> +name: C++ workflow
(further to discussion) How does this look?

<img width="469" alt="image" src="https://user-images.githubusercontent.com/22725053/202078417-dc5add15-014d-49dd-8740-4ef65ce380e2.png">

2022-11-16 15:50 UTC, nucleogenic commented on .github/workflows/build_code.yml
> +    uses: akuker/RASCSI/.github/workflows/arm_cross_compile.yml@nucleogenic-update-github-actions
@akuker I've updated this reference now. It's a bit awkward that this step is needed, but I don't imagine we'll update the cross-compile steps that frequently. We can always revert to sequential execution or a non-DRY implementation if it becomes problematic.

2022-11-18 03:11 UTC, akuker commented on .github/workflows/cpp.yml
> +name: C++ workflow
Perfect. Thanks!

2022-11-18 03:11 UTC, akuker approved these changes

2022-11-18 13:58 UTC, merged

2022-11-18 14:36 UTC, nucleogenic commented
Thanks @uweseimet, I agree. I've raised a draft PR for this, but will test on my fork to keep the PR history here clean.